language: java
jdk:
  - oraclejdk8
  - openjdk8

sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - 'chmod +x mvnw'
  - 'docker-compose up -d'

install: true

script:
  - ./mvnw clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  except:
  - /experimental-.*/

notifications:
  slack: hekate-io:tSiGS0Suj7vrmJN0tlTXw9xn